zuul:
  routes:
    empleado:
      path: /empleado/**
      url: http://localhost:9002/api/empleado/
    cliente:
      path: /cliente/**
      url: http://localhost:9002/api/cliente/
    obra:
      path: /obra/**
      url: http://localhost:9002/api/obra/
    pedido:
      path: /pedido/**
      url: http://localhost:9000/api/pedido/
    material:
      path: /material/**
      url: http://localhost:9001/api/material

eureka:
  client:
    enabled: false